### PR TITLE
Checkout Form Updates

### LINKED ISSUE #695: UAT: Checkout Drawer Incorrect Styling
There are currently various inconsistencies within the checkout drawer, including text and styling issues. Issues should be resolved to adhere to current design. 

Issue 11: https://wiki.corp.magento.com/display/FF/Venia+UX+Issues 

Corrections Include: 
Prompt text color #C0123F
Get it by pre-populated with a default shipping method
Place order changed to "Confirm Order"
Disabled button style for "Confirm Order" updated to "medium" size, light gray, fill style
Cancel button added - this will lead the user back to the first cart state
Currently, the rows have to be filled in order from top to bottom. The original intent was for the user to be able to begin where they wanted to, so all rows should be clickable / editable
The confirm order button converts to an enabled state (dark gray fill) when all required information is filled out
Once a section is filled out, an edit icon needs to display next to it like on "get it by"

## This issue is for the following packages:

- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### PR DESCRIPTION
**Pull request by supernova-at**
## Description

At the heart of this PR is the ability for users to fill out the checkout sections (shipping address, payment method / billing address, and shipping method) in any order, and to cancel out of the checkout flow, and providing a default shipping method.

There are also some CSS changes that include the addition of edit icons for filled in sections, and proper button and text colors.

Lastly, this PR fixes a bug I found along the way where we were submitting an incorrect billing address if the user selected "Billing Address same as Shipping Address" but then going back and editing their shipping address.

## Related Issue

Closes #695.

## Motivation and Context

@soumya-ashok ran some user acceptance testing and came up with a list of things to fix related to checkout in #695. Each of the things she identified is fixed by this PR.

## How Has This Been Tested?

You'll want to run through checkout a bunch of different ways and ensure each path leads to a successful submission. For example:

1. Shipping address > Payment method (keep billing same as shipping) > Submit
1. Shipping address > Payment method (enter different billing address) > Submit
1. Payment method (keep billing same as shipping) > Shipping address > Submit
1. Payment method (enter different billing address) > Shipping address) > Submit

## Screenshots (if appropriate):

screen shot 2019-01-31 at 12 24 09 pm

Things to notice:
  1. The shipping method has a default
  1. Users can fill out the sections in any order
  1. There is a new "Cancel" button
  1. The prompt text color is updated
  1. Button says "Confirm Order" instead of "Place Order"
  1. "Confirm Order" button is gray when disabled

screen shot 2019-01-31 at 12 24 30 pm

Things to notice:
  1. Once a section is filled out, an edit icon appears
  1. "Confirm Order" button becomes enabled when all sections have been filled in
  1. "Confirm Order" button is black (standard button color) when enabled

## Proposed Labels for Change Type/Package

BUG, FEATURE

This PR is 100% in `venia-concept`.

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have linked an issue to this PR.
- [x] I have indicated the change type and relevant package(s).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All CI checks are green (linting, build/deploy, etc).
- [ ] At least one core contributor has approved this PR.

### CODE REVIEW

File: packages/venia-concept/src/components/Checkout/form.js [hunk 1]
```diff
@@ -1,22 +1,22 @@
...
 import Section from './section';
 import ShippingForm from './shippingForm';
 import SubmitButton from './submitButton';
 
 import classify from 'src/classify';
+import Button from 'src/components/Button';
 import defaultClasses from './form.css';
 
-const { BrowserPersistence } = Util;
-const storage = new BrowserPersistence();
```
Comment (zetlen) [inline packages/venia-concept/src/components/Checkout/form.js]: It's always great to see one of these going away. 🙌

File: packages/venia-concept/src/components/Checkout/section.js [hunk 2]
```diff
@@ -1,33 +1,40 @@
...
 import { bool, node, shape, string } from 'prop-types';
-import CheckIcon from 'react-feather/dist/icons/check';
+import EditIcon from 'react-feather/dist/icons/edit-2';
 
 import classify from 'src/classify';
 import Icon from 'src/components/Icon';
 import defaultClasses from './section.css';
 
+const editIconAttrs = {
+    color: 'black',
```
Comment (zetlen) [inline packages/venia-concept/src/components/Checkout/section.js]: Can you add a TODO for moving these attributes into a stylesheet? We want to colocate interdependent things like pixel width, but we don't have an agreed-upon means of doing it yet. (I favor using a CSS Modules [:export block](https://github.com/css-modules/icss#export), but any choice will need @jimbo to weigh in, and can come after release.

File: packages/venia-concept/src/components/Checkout/wrapper.js [hunk 3]
```diff
@@ -16,53 +15,51 @@ import {
...
         beginCheckout: func.isRequired,
+        cancelCheckout: func.isRequired,
         cart: shape({
             details: object,
             guestCartId: string,
             shippingMethods: array,
             totals: object
         }),
         checkout: shape({
+            billingAddress: object, // TODO: shape
```
Comment (sirugh) [inline packages/venia-concept/src/components/Checkout/wrapper.js]: Resolve this and other TODOs? Or if we need to wait for something else can we open an issue to resolve?

File: packages/venia-concept/src/actions/checkout/asyncActions.js [hunk 4]
```diff
@@ -134,14 +158,21 @@ export const submitShippingMethod = payload =>
...
-        const desiredShippingMethod = payload.formValues.shippingMethod;
+        const paymentMethod = await retrievePaymentMethod();
         const shipping_address = await retrieveShippingAddress();
+        const shipping_method = await retrieveShippingMethod();
 
-        // Remove extranneous properties from the billing address because the
-        // Magento backend will reject them.
-        billing_address = removeInvalidKeysFromAddress(billing_address);
+        if (billing_address.sameAsShippingAddress) {
+            billing_address = shipping_address;
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: This is the action associated with submitting the order, so I believe it occurs on the final click. Any changes upstream such as if the user goes back and changes from "same as shipping addr" to a manually entered billing address should update the prop and then this condition would be false.

File: packages/venia-concept/src/actions/checkout/asyncActions.js [hunk 5]
```diff
@@ -134,14 +158,21 @@ export const submitShippingMethod = payload =>
...
+        } else {
+            billing_address = {
+                ...shipping_address,
```
Comment (sirugh) [inline packages/venia-concept/src/actions/checkout/asyncActions.js]: Why do we merge the address objects here?

File: packages/venia-concept/src/components/Checkout/wrapper.js [hunk 6]
```diff
@@ -92,33 +88,29 @@ class CheckoutWrapper extends Component {
...
             submitShippingMethod
         };
 
         const { shippingMethods: availableShippingMethods } = cart;
-        const { paymentData, shippingMethod, shippingTitle } = checkout;
+        const { paymentData, shippingAddress, shippingMethod } = checkout;
 
         const miscProps = {
             availableShippingMethods,
+            havePaymentMethod: hasData(paymentData),
```
Comment (sirugh) [inline packages/venia-concept/src/components/Checkout/wrapper.js]: I usually like `has` over `have`. Just... you know, incase you wanted to change it.

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: > Or, do all user changes to either address flow through this code, and so it's safe to do this?

Correct, and this changeset facilitates that. This now happens *only* when placing the order (we're in `submitOrder` here), so it is too late to change either address.

File: packages/venia-concept/src/components/Checkout/form.js (hunk 1 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/form.js]: Yeah I moved this logic up to the wrapping component `Checkout/wrapper.js`, which is now the only one hooked up to Redux and aware of storage. It passes all that information down to the checkout form via `props`.

File: packages/venia-concept/src/actions/checkout/asyncActions.js [hunk 7]
```diff
@@ -16,7 +12,21 @@ const { request } = RestApi.Magento2;
 const { BrowserPersistence } = Util;
 const storage = new BrowserPersistence();
 
-const INVALID_ADDRESS_KEYS = ['sameAsShippingAddress'];
+// Use the "flatrate" shipping method as the default.
+export const DEFAULT_SHIPPING_METHOD = {
+    amount: 5,
```
[the remark this answers is not in the document]
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: Good call, I'll have to think about that.

Ideally our default is simply the first shipping method returned from `estimate-shipping-methods`, but that happened too late in the process to default the checkout form with it, and it didn't make sense anywhere earlier in the process.

File: packages/venia-concept/src/components/Checkout/wrapper.js (hunk 3 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/wrapper.js]: Oops, thanks

File: packages/venia-concept/src/actions/checkout/asyncActions.js [hunk 8]
```diff
@@ -25,6 +35,11 @@ export const beginCheckout = () =>
         dispatch(getCountries());
     };
 
+export const cancelCheckout = () =>
+    async function thunk(dispatch) {
+        dispatch(actions.reset());
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: Speaking of, if we do this work here should we close #792?

File: packages/venia-concept/src/components/Checkout/wrapper.js (hunk 6 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/wrapper.js]: I don't feel too strongly about it aside from the fact that the consuming code is doing `if (!havePaymentMethod)`, which - in english - reads nicer than `if (!hasPaymentMethod)` but I'm really splitting hairs here 😄

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: Good ping, I may have misunderstood @soumya-ashok 's intent.

File: packages/venia-concept/src/components/Checkout/wrapper.js [hunk 9]
```diff
@@ -16,53 +15,51 @@ import {
...
-        isShippingMethodReady(checkout)
+    const {
+        billingAddress,
+        paymentData,
+        shippingAddress,
+        shippingMethod
+    } = checkout;
+
+    return [billingAddress, paymentData, shippingAddress, shippingMethod].every(
+        hasData
```
Comment (jimbo) [inline packages/venia-concept/src/components/Checkout/wrapper.js]: You can just use `.every(Boolean)` here.

File: packages/venia-concept/src/components/Checkout/section.js (hunk 2 above)
Comment (jimbo) [reply packages/venia-concept/src/components/Checkout/section.js]: I like the idea of the export block (and the comment). Also agree that we should do it project-wide after the release.

File: packages/venia-concept/src/components/Checkout/section.js [hunk 10]
```diff
@@ -1,33 +1,40 @@
...
+    width: 18
+};
+const EDIT_ICON = <Icon src={EditIcon} attrs={editIconAttrs} />;
```
Comment (jimbo) [inline packages/venia-concept/src/components/Checkout/section.js]: Good use of a static element here.

File: packages/venia-concept/src/components/Checkout/form.js [hunk 11]
```diff
@@ -222,26 +202,56 @@ class Form extends Component {
...
+                year: 'numeric'
+            }
+        );
+
         return (
             <Fragment>
-                <strong>{shippingTitle}</strong>
+                <strong>{twoDaysFromNowDisplay}</strong>
+                <br />
+                <span>{shippingTitle}</span>
```
Comment (jimbo) [inline packages/venia-concept/src/components/Checkout/form.js]: I've already discussed with @soumya-ashok why we shouldn't do this.

If the shopper is ordering on a Friday, is this telling them it'll be there by Sunday? Should this function be aware of holidays? Does it know if the shipper ships on weekends? Of course not.

"Estimated ship date" is not a mathematical calculation; it's a logistical one. Worse, a shopper is likely to interpret it as a guarantee, even if we were to add an explicit disclaimer that it's not—and they'll be upset accordingly.

If we get a ship date back from the API, that's one thing, but this shouldn't be client-side. 😅

File: packages/venia-concept/src/components/Checkout/wrapper.js (hunk 3 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/wrapper.js]: Resolved by https://github.com/magento-research/pwa-studio/pull/799/commits/fb3ab5b146b877d59168c9d108a9adb38b48b982.

File: packages/venia-concept/src/actions/checkout/asyncActions.js [hunk 12]
```diff
@@ -134,14 +158,21 @@ export const submitShippingMethod = payload =>
...
-        // Remove extranneous properties from the billing address because the
-        // Magento backend will reject them.
-        billing_address = removeInvalidKeysFromAddress(billing_address);
+        if (billing_address.sameAsShippingAddress) {
+            billing_address = shipping_address;
+        } else {
+            billing_address = {
+                ...shipping_address,
+                ...billing_address
+            };
```
Comment (jimbo) [inline packages/venia-concept/src/actions/checkout/asyncActions.js]: This seems like it could have unintended effects. Is it possible for `shipping_address` to have property values that `billing_address` does not?

```es6
const a = { first: "Austin", middle: "Danger", last: "Powers" }
const b = { first: "Vanessa", last: "Kensington" }
const c = { ...a, ...b }

log(c) // { first: "Vanessa", middle: "Danger", last: "Kensington" }
```

File: packages/venia-concept/src/components/Checkout/wrapper.js (hunk 6 above)
Comment (jimbo) [reply packages/venia-concept/src/components/Checkout/wrapper.js]: I've never seen `haveData` before. @sirugh is right, IMO.

File: packages/venia-concept/src/components/Checkout/form.js (hunk 11 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/form.js]: Good points, I was unaware!

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 12 above)
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: Yes, `shipping_address` definitely does have properties that `billing_address` does not (`firstname`, `lastname`, and `email`, specifically). I'm basically piggybacking those values from `shipping_address` here because the M2 will reject the `billing_address` if it doesn't contain them.

File: packages/venia-concept/src/components/Checkout/form.js (hunk 11 above)
Comment (soumya-ashok) [reply packages/venia-concept/src/components/Checkout/form.js]: @supernova-at I'm sorry I missed the preset ship date - I was too caught up with all the other details. Thanks for your work on this!

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (soumya-ashok) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: @sirugh and @supernova-at This comes back to the point I was making and have made multiple times now. The cart is supposed to have a mask on it once the user enters checkout as far as the current design intent is concerned. The cancel is intended to take them back to the shopping cart. If we're not going to be able to make the cart unavailable when they enter checkout, we need to discuss an alternate flow.

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 12 above)
Comment (sirugh) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: I think it'd be fine to just explicitly copy those props into the object here rather than spreading the entire shipping address in that case.

File: packages/venia-concept/src/components/Checkout/wrapper.js (hunk 9 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/wrapper.js]: I do like the simplicity of `.every(Boolean)` but `.every(hasData)` makes it explicit what we're testing for and avoids some mental overhead for the reader.

I'm fine with either, really, but unless you feel strongly I'd like to keep this as is.

File: packages/venia-concept/src/components/Checkout/form.js (hunk 11 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/form.js]: I will update this to match the mock:

screen shot 2019-02-01 at 11 06 56 am

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: I was actually able to remove this entirely now that we're not defaulting the field 🎉 

https://github.com/magento-research/pwa-studio/pull/799/commits/7244054a1cbbf369e19126a3e22b77fa0800d24c

File: packages/venia-concept/src/reducers/checkout.js [hunk 13]
```diff
@@ -24,8 +27,28 @@ const initialState = {
...
+        const storedPaymentMethod = storage.getItem('paymentMethod');
+        const storedShippingAddress = storage.getItem('shipping_address');
+        let storedShippingMethod = storage.getItem('shippingMethod');
+
+        // If we didn't have a stored shipping method already,
+        // use the default one and then save the default one to storage for next time.
+        if (!storedShippingMethod) {
+            storedShippingMethod = DEFAULT_SHIPPING_METHOD;
+            saveShippingMethod(DEFAULT_SHIPPING_METHOD);
+        }
```
[the remark this answers is not in the document]
Comment (supernova-at) [reply packages/venia-concept/src/reducers/checkout.js]: I was able to remove this entirely in https://github.com/magento-research/pwa-studio/pull/799/commits/7244054a1cbbf369e19126a3e22b77fa0800d24c now that we're not defaulting the shipping method 👍

File: packages/venia-concept/src/components/Checkout/form.js (hunk 11 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/form.js]: Resolved in https://github.com/magento-research/pwa-studio/pull/799/commits/7244054a1cbbf369e19126a3e22b77fa0800d24c.

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: Sounds like a plan 👍 .

I updated the button text to "Back to Cart" in https://github.com/magento-research/pwa-studio/pull/799/commits/9d8ddff723e373b8fd18c67307f25348466d207e.

I'll move on to #717 immediately after this.

File: packages/venia-concept/src/actions/checkout/asyncActions.js (hunk 12 above)
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: Resolved in https://github.com/magento-research/pwa-studio/pull/799/commits/6b34063e9a9b2d4e48eacd4c544f6dc1770e9d9e.

File: packages/venia-concept/src/components/Checkout/wrapper.js (hunk 6 above)
Comment (supernova-at) [reply packages/venia-concept/src/components/Checkout/wrapper.js]: Resolved in https://github.com/magento-research/pwa-studio/pull/799/commits/bc395d699d381b578cd3d88bbc8b6ea35e728fca.

File: packages/venia-concept/src/actions/checkout/asyncActions.js [hunk 14]
```diff
@@ -1,11 +1,7 @@
 import { RestApi, Util } from '@magento/peregrine';
 
 import { closeDrawer } from 'src/actions/app';
-import {
-    clearGuestCartId,
-    getCartDetails,
-    getShippingMethods
-} from 'src/actions/cart';
+import { clearGuestCartId, getShippingMethods } from 'src/actions/cart';
```
[the remark this answers is not in the document]
Comment (supernova-at) [reply packages/venia-concept/src/actions/checkout/asyncActions.js]: Resolved in https://github.com/magento-research/pwa-studio/pull/799/commits/af961b8fb613ba9fc8910fe93d492b2f3997fc3b.

File: packages/venia-concept/src/components/Checkout/shippingForm.js [hunk 15]
```diff
@@ -37,11 +37,19 @@ class ShippingForm extends Component {
...
+        let selectableShippingMethods;
+
+        if (availableShippingMethods.length) {
+            selectableShippingMethods = availableShippingMethods.map(
+                ({ code, title }) => ({ label: title, value: code })
+            );
+            initialValue =
+                shippingMethod || availableShippingMethods[0].carrier_code;
+        } else {
+            selectableShippingMethods = [];
```
Comment (sirugh) [inline packages/venia-concept/src/components/Checkout/shippingForm.js]: You can default these values above and get rid of this block.
