### PR TITLE
[bug]: Incorrect Order Id Displayed - Replacing functionality

### LINKED ISSUE #816: [BUG] Update Content of Checkout Receipt
Description:
After placing an order on Venia store front, Order Number displayed on Venia store front is different than order number displayed on Admin UI.

1. Go to Venia storefront and a add product to cart.
2. Complete the order checkout process (Place the order).
3. Note the order number displayed on storefront and compare the same on Admin UI >Sales>Order

Expected behavior:
Order number should be the same.

Actual:
Order number are different.

## Proposed Solution
Given limitations of the REST API, we're not able to retrieve the External/Sequence ID for guest users w/o implementation of admin REST access functionality into UPWARD, which we'd prefer not to do. We will instead modify the content of the order receipt to instead display a more general message, which you can find mocks for in a comment below.

### PR DESCRIPTION
**Pull request by sirugh**
## Description
1. Refactor `Receipt` to be a functional component.
1. Remove order ID text from display.
2. Add "View Order Details" button for authed users. Currently no-op as there is no order details page.
3. Update text/style to match mock.

## Related Issue

Closes #816.

## Verification Steps

1. As an authed user, check out and view the receipt. Should match mocks.
2. As a guest, check out and view the receipt. Should match mocks.

## How Have YOU Tested this?
Verification steps above!

## Proposed Labels for Change Type/Package

- [ ] major (e.g x.0.0 - a breaking change)
- [ ] minor (e.g 0.x.0 - a backwards compatible addition)
- [x] patch (e.g 0.0.x - a bug fix)

## Checklist:

- [ ] I have updated the documentation accordingly, if necessary.
- [ ] I have added tests to cover my changes, if necessary.

### CODE REVIEW

File: packages/venia-concept/src/components/Checkout/Receipt/receipt.js [hunk 1]
```diff
@@ -1,93 +1,91 @@
...
+            <div className={classes.body}>
+                <h2 className={classes.header}>Thank you for your purchase!</h2>
+                <div className={classes.textBlock}>
+                    You will receive an order confirmation email with order
+                    status and other details.
+                    <br />
+                    {user.isSignedIn &&
+                        'You can also visit your account page for more information.'}
+                </div>
+                {user.isSignedIn && (
```
Comment (tjwiebell) [inline packages/venia-concept/src/components/Checkout/Receipt/receipt.js]: Can we adjust styles to get rid of these repetitive ifs, and use a ternary?

```jsx
{user.isSignedIn ? (
    // signed in logic
) : (
    // not signed in logic
)}
```

File: packages/venia-concept/src/components/Checkout/Receipt/receipt.js [hunk 2]
```diff
@@ -1,93 +1,91 @@
...
+    const handleCreateAccount = useCallback(() => {
+        createAccount(history);
+    }, [createAccount, history]);
 
-    continueShopping = () => {
-        this.props.continueShopping(this.props.history);
-    };
+    const handleViewOrderDetails = useCallback(() => {
+        // TODO: Implement/connect/redirect to order details page.
+    }, [props.order]);
```
Comment (tjwiebell) [inline packages/venia-concept/src/components/Checkout/Receipt/receipt.js]: Consider destructure (not sure if we advise against mixed use)

File: packages/venia-concept/src/components/Checkout/Receipt/receipt.js [hunk 3]
```diff
@@ -1,93 +1,91 @@
...
+import React, { Fragment, useCallback, useEffect } from 'react';
 import { bool, func, shape, string } from 'prop-types';
-import classify from 'src/classify';
+import { mergeClasses } from 'src/classify';
 import Button from 'src/components/Button';
 import defaultClasses from './receipt.css';
 
-export const CONTINUE_SHOPPING_BUTTON_ID = 'continue-shopping-button';
+export const VIEW_ORDER_DETAILS_BUTTON_ID = 'view-order-details-button';
 export const CREATE_ACCOUNT_BUTTON_ID = 'create-account-button';
```
[the remark this answers is not in the document]
Comment (sirugh) [reply packages/venia-concept/src/components/Checkout/Receipt/receipt.js]: I'm confused -- they are in the code here passed as props to `Button`. Are you saying that we don't use the them after that? I imagine they'd be visible on the rendered HTML for whatever reason. Maybe this was created for a11y?

[the remark this answers is not in the document]
Comment (sirugh) [reply packages/venia-concept/src/components/Checkout/Receipt/receipt.js]: @supernova-at @jimbo do ya'll know why these constants exist?

[the remark this answers is not in the document]
Comment (sirugh) [reply packages/venia-concept/src/components/Checkout/Receipt/receipt.js]: Ok I see -- we were using them to test them in `receipt.spec.js`. I'm going to leave them.

[the remark this answers is not in the document]
Comment (tjwiebell) [reply packages/venia-concept/src/components/Checkout/Receipt/receipt.js]: Ah. Since the receipt only contains a single button now, this _probably_ isn't needed anymore, but I'm fine leaving as-is.

File: packages/venia-concept/src/components/Checkout/Receipt/receipt.js (hunk 1 above)
Comment (tjwiebell) [reply packages/venia-concept/src/components/Checkout/Receipt/receipt.js]: Sorry, my intention here was to just contain all the signed in logic, something like this.

```jsx
return (
    <div className={classes.root}>
        <div className={classes.body}>
            <h2 className={classes.header}>Thank you for your purchase!</h2>
            <div className={classes.textBlock}>
                You will receive an order confirmation email with order
                status and other details.
            </div>
            {user.isSignedIn ? (
                <Fragment>
                    <div className={classes.textBlock}>
                        You can also visit your account page for more information.
                    </div>
                    <Button
                        data-id={VIEW_ORDER_DETAILS_BUTTON_ID}
                        onClick={handleViewOrderDetails}
                    >
                        View Order Details
                    </Button>
                </Fragment>
            ) : (
                <Fragment>
                    <hr />
                    <div className={classes.textBlock}>
                        Track order status and earn rewards for your
                        purchase by creating and account.
                    </div>
                    <Button
                        data-id={CREATE_ACCOUNT_BUTTON_ID}
                        priority="high"
                        onClick={handleCreateAccount}
                    >
                        Create an Account
                    </Button>
                </Fragment>
            )}
        </div>
    </div>
);
```

**Comment by sirugh** [comment]
Updated with last bit of feedback. This is how they look:

[Image from Gyazo](https://gyazo.com/aac7e06f860f3133c764260e003ebf5a)

**Comment by dpatil-magento** [comment]
@sirugh "...by creating and account"     should it be "...by creating an account"  , typo?

File: packages/venia-concept/src/components/Checkout/Receipt/receipt.js [hunk 4]
```diff
@@ -1,93 +1,79 @@
...
+                        <Button onClick={handleViewOrderDetails}>
+                            View Order Details
+                        </Button>
+                    </Fragment>
+                ) : (
+                    <Fragment>
+                        <hr />
+                        <div className={classes.textBlock}>
+                            Track order status and earn rewards for your
+                            purchase by creating and account.
```
Comment (sirugh) [inline packages/venia-concept/src/components/Checkout/Receipt/receipt.js]:
```suggestion
                            purchase by creating an account.
```

File: packages/venia-concept/src/components/Checkout/Receipt/__tests__/__snapshots__/receipt.spec.js.snap [hunk 5]
```diff
@@ -15,36 +15,16 @@ exports[`renders a Receipt component correctly 1`] = `
...
-        className="content"
-      >
-        Continue Shopping
-      </span>
-    </button>
+    <hr />
     <div
       className="textBlock"
     >
       Track order status and earn rewards for your purchase by creating and account.
```
Comment (sirugh) [inline packages/venia-concept/src/components/Checkout/Receipt/__tests__/__snapshots__/receipt.spec.js.snap]:
```suggestion
      Track order status and earn rewards for your purchase by creating an account.
```

**Comment by sirugh** [comment]
@dpatil-magento fixed

**Comment by dpatil-magento** [comment]
QA Pass. Waiting for #20 to get merged.
